Changes Amazon
nickspaargaren/no-amazon pull request #14
Opened 2022-01-12 12:33 UTC by gallegonovato

2022-01-12 15:32 UTC, nickspaargaren requested changes

2022-01-12 15:51 UTC, gallegonovato commented on amazon.txt
> +cdn.jsdelivr.net
Done

2022-01-12 15:54 UTC, gallegonovato commented on amazon.txt
> +amazon.com
Done

2022-01-13 09:05 UTC, nickspaargaren requested changes
After these changes we can merge them!

2022-01-13 09:05 UTC, nickspaargaren commented on amazon.txt
> +amazeamazon.ddns.net
```suggestion
```

This is not a Amazon domain

2022-01-13 09:05 UTC, nickspaargaren commented on amazon.txt
> +amazon34.duckdns.org
```suggestion
```

This is not a Amazon domain

2022-01-13 11:04 UTC, gallegonovato commented on amazon.txt
> +amazon34.duckdns.org
Delete

2022-01-13 11:04 UTC, gallegonovato commented on amazon.txt
> +amazeamazon.ddns.net
Delete

2022-01-13 11:06 UTC, nickspaargaren requested changes

2022-01-13 11:06 UTC, nickspaargaren commented on amazon.txt
> +yourmailamazon99.redirectme.net
```suggestion
```

2022-01-13 11:07 UTC, gallegonovato commented
Good morning:

Changes made. :)

I don't know what you think about making a GAFAM , of a hosts to avoid the Windows stuff like https://github.com/nickspaargaren/no-amazon/issues/4 comments.

Best regards

2022-01-13 11:08 UTC, gallegonovato commented on amazon.txt
> +yourmailamazon99.redirectme.net
Delete

2022-01-13 11:09 UTC, nickspaargaren approved these changes

2022-01-13 11:09 UTC, merged